### PR TITLE
SLAP file storage

### LINKED ISSUE #32: Transfer saved data into another computer
As a student, I want to be able to extract information from one computer to the other so I am able to sync information between multiple devices.

### LINKED ISSUE #140: Code Review for @Woolicious98
@Woolicious98
#### ModuleStorage.java
- [ ] Line 139: `if (!CommonUtils.isValidFileName(mod) || !mod.matches(CommonFormat.SPACE_NEGATED_DELIMITER) || !mod.equals(`, the comparison got quite complicated so you would want to consider using a boolean to break up the comparison then store the result individually.

- [ ] Line 414: `} else if (!CommonUtils.isValidFileName(CommonUtils.getFileNameOnly(file.getName()))) {`, you can consider extracting the inner value `CommonUtils.getFileNameOnly(file.getName()))` to a variable then using it so it won't be so "nested".

#### CommonUtils.java
- [ ] Line 193: May want to extract the `"\\."` so it is not a magic literal.

### LINKED ISSUE #177: [PE-D] Malformed/Missing JSON fields not checked during processing
Given a case where the `main.json` is corrupted/wrongfully edited, the program will produce a NullPointerException when navigating to the relevant menu or accessing the relevant data.

For instance, a missing day field for one of the events

Results in a NullPointerException

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: exetr/ped#5

### PR DESCRIPTION
**Pull request by Woolicious98**
Closes #177 
Closes #140 
Closes #32

### CODE REVIEW

File: src/main/java/terminus/storage/NoteStorage.java [hunk 1]
```diff
@@ -0,0 +1,162 @@
...
+                        String noteName = CommonUtils.getFileNameOnly(file.getName());
+                        Note newNote = new Note(noteName, data);
+                        contentManager.add(newNote);
+                    }
+                } catch (Exception e) {
+                    // Ignore all exception and skip the file
+                }
+            }
+        }
+    }
```
Comment (3m0W33D) [inline src/main/java/terminus/storage/NoteStorage.java:117]: Maybe replace this is a filter? and a after foreach? Since the try catch is localized?

**Review by 3m0W33D — APPROVED** [review]
Amazing LGTM!

File: src/main/java/terminus/storage/NoteStorage.java (hunk 1 above)
Comment (Woolicious98) [reply src/main/java/terminus/storage/NoteStorage.java]: okay done!

File: src/main/java/terminus/storage/FilterManager.java [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+        } else if (!module.matches(CommonFormat.SPACE_NEGATED_DELIMITER)) {
+            isValid = false;
+        } else if (!module.equals(module.toUpperCase())) {
+            isValid = false;
+        }
+        return isValid;
+    }
+
+    /**
+     * Checks if given QUestion object is valid for TermiNUS.
```
Comment (kelvneo) [inline src/main/java/terminus/storage/FilterManager.java:101]: Typo

File: src/main/java/terminus/storage/FilterManager.java [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+            }
+            CommonUtils.convertToLocalTime(link.getStartTime().toString());
+            if (CommonUtils.hasDurationOverflow(link.getStartTime(), link.getDuration())) {
+                isValid = false;
+            }
+        } catch (InvalidArgumentException e) {
+            isValid = false;
+        }
+        return isValid;
+    }
```
Comment (kelvneo) [inline src/main/java/terminus/storage/FilterManager.java:143]: Is it possible to expose these methods as public static methods? It might be useful to prevent repeating code.

**Review by kelvneo — APPROVED** [review]
LGTM
