### PR TITLE
Merge branch-fix to master

### LINKED ISSUE #61: Class display message and DeleteCommand code issues.
Change the display message for class to remove the packages name and for the delete notes to fix the bug of setNote to a generic set method.

### LINKED ISSUE #62: Unexpected synchronization of ArrayList between Schedule and Note
There is an unexpected bug when creating a Schedule, and viewing it in Note workspace, it is visible. 
Not the intended action

### PR DESCRIPTION
**Pull request by Woolicious98**
Resolve issues with DeleteCommand and edited Messages to be more useful and change AddCommand for note to AddNoteCommand.

Closes #61 
Closes #62

### CODE REVIEW

File: src/main/java/terminus/command/DeleteCommand.java [hunk 1]
```diff
@@ -44,8 +44,9 @@ public CommandResult execute(Ui ui, NusModule module) throws InvalidArgumentExce
         ContentManager contentManager = module.getContentManager();
         contentManager.setContent(module.get(type));
         String deletedContentName = contentManager.deleteContent(itemNumber);
-        module.setNotes(contentManager.getContents());
-        ui.printSection(String.format(Messages.MESSAGE_RESPONSE_DELETE, type, deletedContentName));
+        module.set(type, contentManager.getContents());
```
Comment (LouisLouis19) [inline src/main/java/terminus/command/DeleteCommand.java:47]: ok, get to differentiate now!

File: src/main/java/terminus/common/CommonFormat.java [hunk 2]
```diff
@@ -43,9 +50,19 @@ public static boolean isArrayEmpty(ArrayList<String> argArray) {
...
-            throw new InvalidTimeFormatException(Messages.ERROR_MESSAGE_INVALID_TIME_FORMAT);
+            throw new InvalidTimeFormatException(
+                    String.format(Messages.ERROR_MESSAGE_INVALID_TIME_FORMAT, LOCAL_TIME_FORMAT));
         }
-        DateTimeFormatter format = DateTimeFormatter.ofPattern(Messages.LOCAL_TIME_FORMAT);
+        DateTimeFormatter format = DateTimeFormatter.ofPattern(LOCAL_TIME_FORMAT);
         return LocalTime.parse(startTime, format);
     }
+
+    public static <T> String getClassName(T type) {
```
Comment (LouisLouis19) [inline src/main/java/terminus/common/CommonFormat.java:60]: well done!

**Review by kelvneo — APPROVED** [review]
